### ISSUE TITLE
Timeout timer may not work properly for long idle period

### ISSUE THREAD

**Issue by andrew-potachits** [rednez/angular-user-idle#111]
**Describe the bug**
We have an application with idle time = 60 mins, timeout = 20min. If I left the application for 60 mins, idle works fine, but timeout timer (this.timer$ in the code) doesn't tick every 1000 msec as expected, but every minute, for some amount if times. it can be first 100 times, or 27, or 130 - I wasn't able to find the pattern.
After some time the timer starts ticking every second (as expected) but because of that initial every-minute-ticks, the overall timeout is invalid.

**To Reproduce**
To reproduce the issue I've referenced the angular-user-idle library and configured the service with the following values:
idle = 60 min 
timeout = 20 min
ping = 3 min
this.userIdle.onTimerStart() subscribed and shows the countdown timer on the UI.

The interesting thing is that if I put the idle time short (5-10 mins) it is not reproduces. It doesn't work on 45 mins and longer.
Also, if I grab the service to my source code and compile the application without --prod, it also works.

So it reproduces on long idle time (45+ mins) and on production build. 

**Expected behavior**
I expect the timer to finish ticking after timeout period expires. Even if it ticks once a minute, it should rely on timeout value, but not on amount of ticks.

**Screenshots**
example of once-a-minute-tick behaviour
![image](https://user-images.githubusercontent.com/3155254/118995208-a2ef8480-b98f-11eb-9251-7e87f59a2fc0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: chrome
 - Version 90.0.4430.212 (Official Build) (64-bit) (cohort: Stable)

**Additional context**
I was able to 'fix' the code by changing the code of this.timer$ observable to use date diff instead of amount of timer ticks. I can create a pull request of just drop the code snipped here if you want.

**Comment by rednez** [comment]
Hi, 
If you can, create PR and I will review it.

**Comment by toski112** [comment]
Now it is now working for short time period
