### ISSUE TITLE
Angular 13 support

### ISSUE THREAD

**Issue by mpscheidt** [rednez/angular-user-idle#135]
Upgrading from Angular 12 to Angular 13 results is not supported.

Please provide a compatible version of Angular User Idle.

**Comment by superjulius** [comment]
Note that there was no issue building Angular 13 app (with angular-user-idle@2.2.7) using node 16.14.2 and npm 8.5.0
Here is an extract of the deps.
```
    "@angular/animations": "^13.3.8",
    "@angular/cdk": "^13.3.7",
    "@angular/common": "^13.3.8",
    "@angular/compiler": "^13.3.8",
    "@angular/core": "^13.3.8",
    "@angular/forms": "^13.3.8",
    "@angular/platform-browser": "^13.3.8",
    "@angular/platform-browser-dynamic": "^13.3.8",
    "@angular/platform-server": "^13.3.8",
    "@angular/router": "^13.3.8",
    "angular-user-idle": "^2.2.7",
```

It is however now failing with npm 8.11.0 with the following error

![image](https://user-images.githubusercontent.com/12696743/172845979-70a80421-adba-43c2-946e-8fa232e22ed4.png)
