### ISSUE TITLE
support for angular14

### ISSUE THREAD

**Issue by jiangyh1024** [rednez/angular-user-idle#138]
currently, I am using version 3.0.0, but still got warning saying that the version of @angular/common should be 13.

Though, it is still working in Angular14

**Comment by joseluiz98** [comment]
Same issue here

**Comment by sthompson-celerity** [comment]
I have tested a number of things in angular 14, and I agree it works fine

**Comment by alihasnain1997** [comment]
I have been trying to install it but getting following error:
![image](https://user-images.githubusercontent.com/41017630/182332209-c4177c77-0dca-4a97-806e-7e5999a04b62.png)

**Comment by jiangyh1024** [comment]
Use npm install --force


发自我的iPhone

------------------ Original ------------------
From: Ali Hasnain ***@***.***&gt;
Date: 周二,8月 2,2022 4:43 下午
To: rednez/angular-user-idle ***@***.***&gt;
Cc: jiangyh1024 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [rednez/angular-user-idle] support for angular14 (Issue #138)





 
I have been trying to install it but getting following error:

**Comment by joseluiz98** [comment]
> I have been trying to install it but getting following error: ![image](https://user-images.githubusercontent.com/41017630/182332209-c4177c77-0dca-4a97-806e-7e5999a04b62.png)

This error is caused due to the lib lackness of official support to Angular 14, but I'm testing it after forcing the install and its working fine, to proceed installing taking the risks, run:

`npm install --legacy-peer-deps ` or `npm i -f`

**Comment by mpscheidt** [comment]
Please add support for Angular 14. Thank you!

**Comment by hokiepokedad2** [comment]
Yes please. Angular 14 support.

**Comment by rednez** [comment]
Hi guys! Why nobody of you does not read readme.md?
> The library was written for my personal needs. So I distribute it "as is" without advanced supporting and change requesting. If you like the library just use it if not then you're free to fork the repo and make what are you want.
