### ISSUE TITLE
How can indicate when user stop being idle ?

### ISSUE THREAD

**Issue by BlackChesire** [rednez/angular-user-idle#141]

**Comment by rednez** [comment]
Read Readme.md

> The library was written for my personal needs. So I distribute it "as is" without advanced supporting and change requesting. If you like the library just use it if not then you're free to fork the repo and make what are you want.

**Comment by BlackChesire** [comment]
I just used a hostListner for mouse movement to rest the timer,
Would like me to open a PR?
