### ISSUE TITLE
Need support for Angular 14

### ISSUE THREAD

**Issue by dsatputeAtPtc** [rednez/angular-user-idle#148]
This library is not supported on Angular 14, please add support for the same.

**Comment by aksdevac** [comment]
its not officially supported but you can update using `--force` option. it should work with v14 & v15.

**Comment by dsatputeAtPtc** [comment]
yeah that's workaround I have applied, but it's not ideal way to do it. Do you have any plans to support it ?

**Comment by aksdevac** [comment]
Hi, I am not an author of this library.  I am also using this in some of my projects.

**Comment by rednez** [comment]
fixed

**Comment by abhinavIntraedge** [comment]
Please publish a new version with angular 24 compatability
