### ISSUE TITLE
How to config user events

### ISSUE THREAD

**Issue by stevensgarcia** [rednez/angular-user-idle#19]
Hi,

Thanks for the package. Works as expected, and is pretty straightforward to understand.

I would like to ask you, if is there a way to set what events change the idle state. I mean, mouse clicks, mouse scroll, cursor moving, current tab is active...,etc, So I can do some logic based on those.

Thanks in advanced.

**Comment by rednez** [comment]
The events are predefined by lib: mousemove, resize, keydown. And this sets is not configurable in current version. Maybe I extend this logic in the next version.
