### ISSUE TITLE
Cannot use with AOT (angular-cli)

### ISSUE THREAD

**Issue by TschlegelCore10** [rednez/angular-user-idle#2]
Angular 4
Using angular-cli

I receive errors when running a production AOT build: `ng build -prod -aot`.
My `node_modules` folder is located in a directory above `/src`.

Errors:
`ERROR in ./src/$$_gendir/app/core/app.module.ngfactory.ts

Module not found: Error: Can't resolve 'angular-user-idle/user-idle.config' in

'/path/to/code/src/$$_gendir/app/core'
resolve 'angular-user-idle/user-idle.config' in '/path/to/code/src/$$_gendir/app/core'
  
Parsed request is a module
  using description file: /path/to/code/package.json (relative path: ./src/$$_gendir/app/core)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /path/to/code/package.json (relative path: ./src/$$_gendir/app/core)
    resolve as module
      /path/to/code/src/$$_gendir/app/core/node_modules doesn't exist or is not a directory
...`

**Comment by jayordway** [comment]
I have this same issue as well.

**Comment by arianul** [comment]
And here as well unfortunately

**Comment by Helen2011** [comment]
Same issue here.

**Comment by amitkhandagale** [comment]
I am also getting same issue.

**Comment by eltharynd** [comment]
same here

**Comment by moghuln** [comment]
Any work around to this issue?

**Comment by moghuln** [comment]
Is there a way to make aot build work with this?

**Comment by eltharynd** [comment]
to be honest i managed to get this working but i'm not sure how as it was a month ago and i forgot what i did.. but i think it was about cleaning / reinstalling / updating all modules

**Comment by moghuln** [comment]
Angular CLI: 1.7.3
Node: 8.10.0
npm: 5.6.0
Angular: 5.2.9
My App is setup with the above config. Please let me know if you have a different config working for you.

**Comment by weijyewang** [comment]
I'm having this problem too. I tried adding 
 ```
"angular-user-idle/*": [
        "../node_modules/angular-user-idle/*"
      ]
```

to tsconfig.app.json under `paths` property but still it does not work

**Comment by costaivo** [comment]
The node module does not have the ts files included, which causes the above error. 
It has only *.d.ts files 
To fix the error i manually downloaded the files from the git project and pasted inside the **node_modules\angular-user-idle**

- user-idle.config.ts
- user-idle.module.ts
- user-idle.service.ts
- user-idle.ts

**Comment by weijyewang** [comment]
@costaivo  thanks. After following your steps, I got new errors:
`ERROR in ./node_modules/angular-user-idle/user-idle.config.ts
Module build failed: Error: c:\projects\vfleet\node_modules\angular-user-idle\user-idle.config.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (c:\projects\vfleet\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
    at plugin.done.then (c:\projects\vfleet\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
ERROR in ./node_modules/angular-user-idle/user-idle.service.ts
Module build failed: Error: c:\projects\vfleet\node_modules\angular-user-idle\user-idle.service.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (c:\projects\vfleet\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
    at plugin.done.then (c:\projects\vfleet\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`

**Comment by rednez** [comment]
@weijyewang Tonight I update version to 1.1.0.
I tested on angular-cli:
- ng serve
- ng build
- ng serve –aot
- ng build --aot
In all cases project compiles successful without any errors.

Please try a new version.

**Comment by weijyewang** [comment]
@rednez the problem still persist for me after I updated to version 1.1.0. I have tried `ng build --prod` and `ng build --aot`. Of course, `ng serve` and `ng build` works just fine.  May I know what CLI version and Angular version were you testing with?

**Comment by rednez** [comment]
@weijyewang Hm... I check `ng build --prod` too and result is OK. See screenshot.
![screen shot 2018-04-04 at 10 14 26](https://user-images.githubusercontent.com/7082902/38294107-7c67135e-37f2-11e8-84ed-7b653466d701.png)

What version of Angular you use? Note that version 1.1.0 needs Angular 5.

**Comment by weijyewang** [comment]
Yes I'm using Angular 5. I think if could be my configs are broken due to my previous attempt. Thanks for your help, I will check it out myself :)

![image](https://user-images.githubusercontent.com/8890603/38294596-eeca35c2-381d-11e8-8d66-178a73980308.png)

**Comment by Helen2011** [comment]
@rednez , wondering have you tried to import module and service as the sample code on version 1.1.0?

I just upgrade to version 1.1.0, build --aot works now, but have issue to run ng server.

With the version 1.1.0, the import will be changed to as the following via auto import (the import from the sample code doesn't work as well)
In my module .ts
`import {UserIdleModule} from "angular-user-idle/user-idle.module";`
In my component .ts
`import {UserIdleService} from "angular-user-idle/user-idle.service";`

ng server gives me the following error:
`ERROR in ./node_modules/angular-user-idle/user-idle.module.ts
Module build failed: Error: C:\workspace\WEDSS\wedminWeb\node_modules\angular-user-idle\user-idle.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\workspace\WEDSS\wedminWeb\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
    at plugin.done.then (C:\workspace\WEDSS\wedminWeb\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
ERROR in ./node_modules/angular-user-idle/user-idle.service.ts
Module build failed: Error: C:\workspace\WEDSS\wedminWeb\node_modules\angular-user-idle\user-idle.service.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\workspace\WEDSS\wedminWeb\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
    at plugin.done.then (C:\workspace\WEDSS\wedminWeb\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)`

**Comment by rednez** [comment]
@Helen2011 Why you use "angular-user-idle**/user-idle.module**" and "angular-user-idle/**user-idle.service**" instead of simple "_angular-user-idle_"? Update your import to "angular-user-idle" and all will works fine.

**Comment by Helen2011** [comment]
@rednez That import was automatically inserted by IDE if I don't type in import.

I had the same issue as @weijyewang mentioned if I simply upgrade version to 1.1.0 with my previous code, so I cleaned up all, and let IDE do the auto import for me.

Now I got it working, looks like the version 1.1.0 needs devDependencies "@angular-devkit/core": "^0.5.5", otherwise it may have issue on ng server.
