### ISSUE TITLE
Support Angular 7

### ISSUE THREAD

**Issue by mtotheoneandonlyk** [rednez/angular-user-idle#23]
Would be awesome to have support for Angular 7. :)

**Comment by rednez** [comment]
Its works with Angular 7.

**Comment by mtotheoneandonlyk** [comment]
Updating from Angular 6 to 7 broke angular-user-idle. Starting with dependency problems, ending with client site console error output regarding hammer.js etc..

**Comment by rednez** [comment]
Please provide your log and package.json.
