### ISSUE TITLE
Ping is not working when already timed out and you startWatching again

### ISSUE THREAD

**Issue by AleG94** [rednez/angular-user-idle#27]
When the 'Timeout' happens, `isTimeout` is set to `true`. After that, if you call `startWatching()` again, the `isTimeout` is not resetted back to `false` so the ping observable will not work. 

EDIT: Maybe this is intentional. Btw you only need to call `resetTimer()` before start watching again for it to work.

**Comment by rednez** [comment]
You answer on your question :) Use resetTimer()
