### ISSUE TITLE
the interval logic causes change detection every second

### ISSUE THREAD

**Issue by pmestrum** [rednez/angular-user-idle#31]
Run the interval outside of the zone, so that change detection is not triggered

https://angular.io/api/core/NgZone#runoutsideangular

**Comment by pmestrum** [comment]
Can be fixed like this:

`

    /**
     * Start watching for user idle and setup timer and ping.
     */
    startWatching() {
      if (this.idleSubscription) {
        this.idleSubscription.unsubscribe();
      }
    
      // If any of user events is not active for idle-seconds when start timer.
      this.idleSubscription = this.idle$
        .pipe(
          bufferTime(5000), // Starting point of detecting of user's inactivity
          filter(arr => !arr.length && !this.isInactivityTimer),
          tap(() => this.isInactivityTimer = true),
          switchMap(() => {
              return this.zone.runOutsideAngular(() => interval(1000).pipe(
                takeUntil(
                  merge(
                    this.activityEvents$,
                    timer(this.idle * 1000).pipe(
                      tap(() => this.timerStart$.next(true))
                    )
                  )
                ),
                finalize(() => (this.isInactivityTimer = false))
                )
              );
            }
          )
        )
        .subscribe();
    
      this.setupTimer(this.timeout);
      this.setupPing(this.ping);
    }
    
    protected setupTimer(timeout: number) {
      this.zone.runOutsideAngular(() => {
        this.timer$ = interval(1000).pipe(
          take(timeout),
          map(() => 1),
          scan((acc, n) => acc + n),
          tap(count => {
            console.log(`timer tick ${count}`);
            if (count === timeout) {
              this.timeout$.next(true);
            }
          })
        );
      });
    }

`

**Comment by rednez** [comment]
Thank you
