### ISSUE TITLE
Timestart Accuracy

### ISSUE THREAD

**Issue by ssaulinn** [rednez/angular-user-idle#35]
Hello, I have this configuration: 
let mii: number = 120;
this.userIdle.setConfigValues({ idle: mii, timeout: mii - (mii * 0.8), ping: mii / 2 });

an this is the event mapping :
**PING: -------Tue Feb 19 2019 12:24:06
PING: -------Tue Feb 19 2019 12:25:06**
Modal: ---- Tue Feb 19 2019 12:25:18
**PING: -------Tue Feb 19 2019 12:26:06
PING: -------Tue Feb 19 2019 12:27:06
PING: -------Tue Feb 19 2019 12:28:06**
Modal: ---- Tue Feb 19 2019 12:28:08
**PING: -------Tue Feb 19 2019 12:29:06
PING: -------Tue Feb 19 2019 12:30:06
PING: -------Tue Feb 19 2019 12:31:06
PING: -------Tue Feb 19 2019 12:32:06
PING: -------Tue Feb 19 2019 12:33:06**
Modal: ---- Tue Feb 19 2019 12:33:27
**PING: -------Tue Feb 19 2019 12:34:06
PING: -------Tue Feb 19 2019 12:35:06**
Modal: ---- Tue Feb 19 2019 12:35:45
**PING: -------Tue Feb 19 2019 12:36:06
PING: -------Tue Feb 19 2019 12:37:06**
Modal: ---- Tue Feb 19 2019 12:37:49
**PING: -------Tue Feb 19 2019 12:38:06
PING: -------Tue Feb 19 2019 12:39:06
PING: -------Tue Feb 19 2019 12:40:06**
Modal: ---- Tue Feb 19 2019 12:40:16
**PING: -------Tue Feb 19 2019 12:41:06
PING: -------Tue Feb 19 2019 12:42:06
PING: -------Tue Feb 19 2019 12:43:06
PING: -------Tue Feb 19 2019 12:44:06**

The idea is every 2 ping modal comes out, but it is not happening.
Any help?

**Comment by rednez** [comment]
You have to provide more details about issue according to GitHub bug report template.
