### ISSUE TITLE
unwanted change detection on ngIf

### ISSUE THREAD

**Issue by naka-mura** [rednez/angular-user-idle#36]
Hi,
if i implement a ngIf with a function call it will be called every second.
I use the version 2.1.1 which included the issue:
#31 the interval logic causes change detection every second

For example i supplemented the angular-user-idle-master project:

`<mat-card-header *ngIf="test()">Timer...`

in TimerComponent:
`test(): boolean {
console.log('***** called *****');
return true;
}`

This function is called every second.

**Comment by naka-mura** [comment]
Hi,
if i implement a ngIf with a function call it will be called every second.
I use the version 2.1.1 included the issue:
 #31 the interval logic causes change detection every second

For example i supplemented the angular-user-idle-master project:

<mat-card-header *ngIf="test()">
    <mat-card-title>Timer</mat-card-title>
  </mat-card-header>

in TimerComponent:
test(): boolean {
      console.log('***** called *****');
      return true;
  }

This call is made every second.

**Comment by derBinder** [comment]
Here is a stackblitz to reproduce it. Just open the console and take a look.
https://stackblitz.com/edit/angular-dsw9m3

**Comment by rednez** [comment]
I can't understand what incorrect in working of lib in your case and what you expect. Your code works like you coded it.

**Comment by derBinder** [comment]
The code is just copied from your documentation.
Take a look in the console, you will see that the test() function is called every second. This is a performance issue, when you call many functions in the HTML code.

**Comment by rednez** [comment]
My library has nothing to do with it. Just remove my library and try to use in ngOnInit() the standard
 setInterval(() => console.log('some interval'), 1000) and you'll see same result.
