### ISSUE TITLE
onTimerStart does not work properly in safari

### ISSUE THREAD

**Issue by tejasberi** [rednez/angular-user-idle#4]
I am using the onTimerStart to clock 1 minute to perform some user action.
When i do userIdle.onTimerStart().subscribe(t => { console.log(t) }); on safari on Mac, lock my computer when the session is idle then the onTimerStart does not console.log anything till the time computer is unlocked.

Where as on the other browsers the counter works properly

**Comment by rednez** [comment]
I confirm a bug but I need time to debug to determine a source of it. I hope I do it in the next version.

**Comment by anupavanm** [comment]
Any update on this ?

**Comment by Y-Taras** [comment]
Is there any workaround to solve this issue on Mac (Safari)?

**Comment by rednez** [comment]
Problem is not in angular-user-idle. This is a specific problem of Safari related on window.setTimeout and window.setInterval.
