### ISSUE TITLE
Doesn't work over IFRAME-s

### ISSUE THREAD

**Issue by vitaly-t** [rednez/angular-user-idle#43]
**Describe the bug**

Doesn't work over IFRAME content.

**Expected behavior**

Not to timeout when the mouse or keyboard input are active inside an IFRAME.

**Additional context**

I have an app with IFRAME taking up the entire app area, so nothing much beside the IFRAME content, and this solution doesn't work at all.

**Comment by rednez** [comment]
A library don’t support iFrame and I don’t to plan to support it in the near future.
