### ISSUE TITLE
Set Config Values

### ISSUE THREAD

**Issue by queejie** [rednez/angular-user-idle#5]
Thanks very much for this module.  I would like to be able to set the config values later in the app, after I have retrieved them via ajax from a database config.  (Different installations will have different timeout values.)    

I can see a getConfigValue(), but no setConfig() or setConfigValue() in the code.  All the values are private.  Do you think you might be able to add a method to set config values?  It would be greatly appreciated!

**Comment by rednez** [comment]
Check version 2.0.0

**Comment by santhoshrajuvysyaraju** [comment]
is Version 2.0.0 will support for angular5
