### ISSUE TITLE
onTimeout() doesn't fire if timeout = 0

### ISSUE THREAD

**Issue by lambidu** [rednez/angular-user-idle#51]
As I can understand, meaning of `idle` and `timeout`, is to be able to show to the user some warning, that some action will take place in `timeout` seconds. 

But, because I don't need that functionality, I've tried to set `{ idle: 900, timeout: 0}`. This broken `onTimeout()` subscription, it never gets any notification, so `onTimeout()` action is never executed.

1. Configure `UserIdleModule.forRoot({ idle: 5, timeout: 0, ping: 0 })`
2. Setup a subscription for `onTimerStart()` and `onTimeout()`
3. Wait 5 seconds to see that nothing happens

**Expected behavior**
Should immediately execute `onTimeout()`

**Comment by DelphiWorlds** [comment]
A workaround might be to set the timeout value to 1

**Comment by lambidu** [comment]
> 
> 
> A workaround might be to set the timeout value to 1

that's what I've did, but will be nice to have it out-of-the box
