### ISSUE TITLE
Angular 8 support

### ISSUE THREAD

**Issue by taysco** [rednez/angular-user-idle#56]
Are you planning to support Angular 8? I see a pull request to add support ... was hoping to get this soon.

**Comment by w0jcik** [comment]
+1 for Angular8 support.

**Comment by cobaltutby** [comment]
yea... not working with Angular 8 for me

**Comment by taysco** [comment]
@cobaltutby the pull request is simply a version update ... not any code changes to "work with" Angular 8. So it should work still, just errors.

**Comment by w0jcik** [comment]
works in angular8, just build throws warning for angular version mismatch.

**Comment by konradst** [comment]
please pull the Angular 8 version dep pretty please https://github.com/rednez/angular-user-idle/pull/55

**Comment by cobaltutby** [comment]
@w0jcik  thanks

**Comment by rednez** [comment]
- PR was pulled directly into master. So I declined it.
- Updating of version in package.json is not critical because library working as in Angular 7. In Angular 8 you just see a warning.

I will make necessary changes in next update.

**Comment by taysco** [comment]
That is incredibly unfortunate. Looks like I'll be forking this.
