### ISSUE TITLE
Does not work when browser is in background

### ISSUE THREAD

**Issue by jainlavish** [rednez/angular-user-idle#58]
**Describe the bug**
**To Reproduce**
1. Run the application in Chrome browser
2. Start the timer on some action and set timeout lets say 10 minutes
3. Minimize the browser for more than 10 minutes
4. Check the browser again, it is not firing Timeout event.

**Expected behavior**
Timeout event should fire even when Chrome is in background or relevant tab is not in focus.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome

**Smartphone (please complete the following information):**
 - Version: 74( Chrome), 2.1.2( angular-user-idle)

**Additional context**

**Comment by rednez** [comment]
It's not a problem of angular-user-idle. It's a feature of browsers to save resources.

**Comment by jainlavish** [comment]
Is there any workaround?
