### ISSUE TITLE
from events not working on angular 5

### ISSUE THREAD

**Issue by MtarantoOa** [rednez/angular-user-idle#59]
Hi, 
Im working with the 1.1.0 version of the library.

We try to see if the timer stops after the user made an acction to the web page:

We saw that on the library code there are the Observables for the actions:

     this.activityEvents$ = Observable.merge(
      Observable.fromEvent(window, 'mousemove'),
      Observable.fromEvent(window, 'resize'),
      Observable.fromEvent(document, 'keydown'));

We add some logs and we noticed that even if you move the mouse or resize the window the timer dont get restarted.

This is how we are configuring the library:

 this.userIdle = new UserIdleService({ idle: 1, timeout: 180, ping: 120 });

 this.userIdle.startWatching();
        this.idleTimeStart = this.userIdle.onTimerStart().subscribe(count => {
            if (count === 60) {
                this.checkSessionModalRef = this.omsnicMessageModal.show({
                    title: 'Close Session',
                    subtitle: 'Are you still there?',
                    type: 'warning',
                    okText: 'Yes',
                    hideCancel: true
                });

                this.checkSessionModalRef.result.then(answer => {
                    if (answer) {
                        this.userIdle.resetTimer();
                    } else {
                        this.endSession();
                    }
                });
            }
        });

        this.idleOnTimeout = this.userIdle
            .onTimeout()
            .subscribe(() => this.endSession());

we are doing something wrong?

Thanks!

**Comment by rednez** [comment]
I don't support Angular 5 and not support 1.1.x branch.
