### ISSUE TITLE
How to update IdleTime value in Angular 5.x version?

### ISSUE THREAD

**Issue by nehaagrawala** [rednez/angular-user-idle#60]
**Describe the bug**
I want to update Idle time value but in angular 5.x, setConfig method is not working.

**Expected behavior**
setConfig  method should also work in Angular 5.x version. So that we can update value of Idle time from anywhere.

**Screenshots**

**Desktop (please complete the following information):**

**Comment by rednez** [comment]
Angular 5.x don't supported.
