### ISSUE TITLE
On close browser idle is not working

### ISSUE THREAD

**Issue by HireHandFor** [rednez/angular-user-idle#63]
When we close the browser(chrome), after idle time +... when users open the logged url there still logged in. 

Users who are not closing the browser and are in idle time, there logged out.

Implemented like examples:
 //Watch for Inactivity
    this.userIdle.startWatching();

    // Watch for the Idle
    this.userIdle.onTimerStart().subscribe();

    // Watch for TimeOut
    this.userIdle.onTimeout().subscribe(() => { this.restart(); this.logout();  });

Is there way to count browser idle time without open browser?

**Comment by pramodvkadam** [comment]
> When we close the browser(chrome), after idle time +... when users open the logged url there still logged in.
> 
> Users who are not closing the browser and are in idle time, there logged out.
> 
> Implemented like examples:
> //Watch for Inactivity
> this.userIdle.startWatching();
> 
> ```
> // Watch for the Idle
> this.userIdle.onTimerStart().subscribe();
> 
> // Watch for TimeOut
> this.userIdle.onTimeout().subscribe(() => { this.restart(); this.logout();  });
> ```
> 
> Is there way to count browser idle time without open browser?

This code only works on the browser open. If you need after close you have to use service worker background processes. They can work on tab/browser close also.
