### ISSUE TITLE
Property 'idleSensitivity' is missing in type '{ idle: number; timeout: number; ping: number; }

### ISSUE THREAD

**Issue by karivka** [rednez/angular-user-idle#64]
Hi,

Today, on ci pipeline server my build(ng build --prod) started failing with error:
[ERROR] ERROR in src/app/app.module.ts(52,32): error TS2345: Argument of type '{ idle: number; timeout: number; ping: number; }' is not assignable to parameter of type 'UserIdleConfig'.
[ERROR]   Property 'idleSensitivity' is missing in type '{ idle: number; timeout: number; ping: number; }'.

My app.module.ts file
UserIdleModule.forRoot({ idle: 1200, timeout: 1, ping: 120 }),

As I understand was introduced new "idleSensitivity" parameter that I have to set in app.module.ts?

**Comment by rednez** [comment]
Check v2.2.1
