### ISSUE TITLE
Idle timeout not working when laptop goes in sleep mode

### ISSUE THREAD

**Issue by sajid506a** [rednez/angular-user-idle#65]
Idle timeout not getting triggered when laptop is in sleep mode

**Comment by sajid506a** [comment]
Set my idle timer at 5 minutss
2 - onIdleStart  
3 - Widows laptop make to  sleep after 2 minutes.
4 - wake
5 - Move mouse on browser and onIdleEnd does not fire.

**Comment by slawiko** [comment]
Unfortunately this use-case was rejected: https://github.com/rednez/angular-user-idle/pull/72
I implemented this in fork though: https://github.com/slawiko/angular-simple-user-idle

**Comment by rednez** [comment]
Hi. As I wrote in readme.md

> The library was written for my personal needs. So I distribute it "as is" without advanced supporting and change requesting. If you like the library just use it if not then you're free to fork the repo and make what are you want.

Sorry but I can't test and fix the lib in all use cases you have found. But for my purposes the lib works fine and as I expected.
