### ISSUE TITLE
Angular 5 project doesn't build prod

### ISSUE THREAD

**Issue by sancho0410** [rednez/angular-user-idle#70]
**Description**
Hi, i have a problem with the packaging with the angular-user-idle@1.1.0 version (use in angular ^5.2.11 project).
I can run "ng build --dev" but i have some compilation issue with "ng build --prod"
I know that this version was not supported, but can run repackage this version (to version 1.1.1 maybe) ? 

Thank a lot

**To Reproduce**
1. Import lib v1.1.0
2. Compile with ng build --dev --> OK
3. Compile with ng build --prod --> KO

**Expected behavior**
ng build --prod compilation OK

**Screenshots**
```ERROR in ./node_modules/angular-user-idle/user-idle.service.ts
Module build failed: Error: C:\Sources\[Project]\node_modules\angular-user-idle\user-idle.service.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\Sources\[Project]\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
    at plugin.done.then (C:\Sources\[Project]\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Desktop:**
 - Browser : Chrome
 - Version : 79

**Additional context**
package build-prod command use : "build-prod": "ng build --prod",

**Comment by rednez** [comment]
I don't support and don't maintain this version as deprecated.

**Comment by sancho0410** [comment]
cool thanks for analyzing the problem
I can understand that repackaging a lib can be difficult and time consuming ;-)

**Comment by rednez** [comment]
Thank to read the README before creating of issue, especially: 
1. Unfortunately, I don't have necessary time to maintenance my library as fast as you can expected.
2. To use this library in Angular 5.x use angular-user-idle ver. 1.1.0 (depreacated and don't supported!)

Have a good day.
