### ISSUE TITLE
Does not work on mobile device when the timespan is set to about 30 minutes

### ISSUE THREAD

**Issue by Sarfarazsajjad** [rednez/angular-user-idle#71]
**Describe the bug**
I have tested it with time set to 15 seconds this works fine on both pc and mobile devices. but when I increase the idle time to around 30 minutes it works only on pc and not on mobile devices
**To Reproduce**
in app.module.ts imports add the following.

    UserIdleModule.forRoot({idle: 1800, timeout: 1, ping: 0}),

then in app.component.ts

    this.userIdle.startWatching();
    this.userIdle.onTimeout().subscribe(() => this.logout());

**Expected behavior**
it should call logout method on mobile device like samsung galaxy s8. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser chrome
 - Version: chrome version 79

**Smartphone (please complete the following information):**
 - Device: s8
 - OS: android 7
 - Browser chrome
 - Version chrome version 79

**Additional context**
it works on Desktop but does not work on mobile

**Comment by mashraf22** [comment]
even it is not working for IPad7 safari browser after keeping idle time 10 min.  It is working when idle time is kept for 2 mins

**Comment by SouengKimmeng** [comment]
I have meet that problem as well, I use angular integrate with PWA and it does not work when I add icon in home screen. Thanks

**Comment by rednez** [comment]
I didn't designed this lib for mobile devices.
