### ISSUE TITLE
Unmet peer dependency

### ISSUE THREAD

**Issue by pooshonbanerjee** [rednez/angular-user-idle#79]
**Describe the bug**
Not sure if this is a bug, just a peer dependency Warning while installing the package.

Warning:

`angular-user-idle@2.2.2 requires a peer of @angular/common@^6.0.0 || ^9.0.0 but none is installed. You must install peer dependencies yourself.`

I have @angular/common@7.2.15 installed, which falls well within 6.0.0 and 9.0.0

**To Reproduce**

run `npm i angular-user-idle`

**Expected behavior**
I think the warning should not appear if @angular/common@version is between 6 and 9, and not 6 or 9.

This package still works fine, no issues there. Just that warning is unnerving.

**Comment by rednez** [comment]
Thanks. I fix it in the next build.
