### ISSUE TITLE
how to set dynamic time

### ISSUE THREAD

**Issue by vivekkbaskaran** [rednez/angular-user-idle#80]
i need to set the time from the API. Please let me know how to achieve this?

**Comment by aedanphntms** [comment]
If you are still having this problem. For dynamic timeout changes I just did something like `updateTimeout(timeout: number) {
    this.userIdle.stopWatching();
    this.userIdle.setConfigValues({idle: 1, timeout: timeout});
    this.userIdle.startWatching();
  }`
