### ISSUE TITLE
How to unsubscribe "this.idle.ping$"

### ISSUE THREAD

**Issue by sanjayhanumegowda** [rednez/angular-user-idle#85]
version:"angular-user-idle": "^2.2.2"

I am subscribing to the "this.idle.ping$.subscribe(() => console.log("PING"));"  on login of my application and calling refresh token for every 10 mins, but when i logout i just need to unsubscribe to "this.idle.ping$" so that i will be able to stop calling refresh token after logout .

Thanks

**Comment by sanjayhanumegowda** [comment]
Hi I did not get any solution for the above problem but the issue has been closed. Was i not appropriate in asking the question?

**Comment by 9marta5** [comment]
Hi,
I've the same problem.

**Comment by sanjayhanumegowda** [comment]
I solved the issue by doing this.

import { Subscription } from 'rxjs';

private pingSubscription: Subscription;

this.pingSubscription = this.userIdle.ping$.subscribe(() =>{
    console.log('do what 
    });

//to unsubscribe 

this.pingSubscription.unsubscribe();

**Comment by 9marta5** [comment]
> I solved the issue by doing this.
> 
> import { Subscription } from 'rxjs';
> 
> private pingSubscription: Subscription;
> 
> startWatching(){
> this.pingSubscription = this.userIdle.ping$.subscribe(() =>{
> console.log('do whatever you want to do');
> });
> }
> 
> //to unsubscribe
> 
> stopWatching(){
> this.pingSubscription.unsubscribe();
> }

Thank you! It works
