### ISSUE TITLE
Angular 10 compatibility

### ISSUE THREAD

**Issue by celvin** [rednez/angular-user-idle#91]
**Describe the bug**
After upgrading to Angular 10 or installing this library into an Angular 10 application I've gotten this message:

angular-user-idle@2.2.2 requires a peer of @angular/common@^6.0.0 || ^9.0.0 but none is installed. You must install peer dependencies yourself

**To Reproduce**
1. install this into an Angular 10 project.

**Expected behavior**
Not to show this warning and get installed within Angular 10

**Comment by rednez** [comment]
I accepted accordingly PR.
